export const DOM = {
  statusBadge: document.getElementById('status-badge'),
  dropZone: document.getElementById('drop-zone'),
  imageUpload: document.getElementById('image-upload'),
  selectBtn: document.getElementById('select-btn'),
  sampleBtn: document.getElementById('sample-btn'),
  uploadContent: document.getElementById('upload-content'),
  previewContainer: document.getElementById('preview-container'),
  imagePreview: document.getElementById('image-preview'),
  removeBtn: document.getElementById('remove-btn'),
  generateBtn: document.getElementById('generate-btn'),
  aiBtnTooltip: document.getElementById('ai-btn-tooltip'),
  generateLoader: document.getElementById('generate-loader'),
  iconSparkle: document.getElementById('icon-sparkle'),
  iconEnhance: document.getElementById('icon-enhance'),
  wittyBubble: document.getElementById('witty-bubble'),
  altTextInput: document.getElementById('alt-text-input'),
  copyBtn: document.getElementById('copy-btn'),
  sampleImageSource: document.getElementById('sample-image-source'),
  postContent: document.getElementById('post-content'),
  shareBtn: document.getElementById('share-btn'),
  successOverlay: document.getElementById('success-overlay'),
  successClose: document.getElementById('success-close'),
  stagingOverlay: document.getElementById('staging-overlay'),
  historyStepper: document.getElementById('history-stepper'),
  historyIndex: document.getElementById('history-index'),
  historyPrev: document.getElementById('history-prev'),
  historyNext: document.getElementById('history-next'),
  btsToggle: document.getElementById('bts-toggle'),
  btsPanel: document.getElementById('bts-panel'),
  btsClose: document.getElementById('bts-close'),
  btsPin: document.getElementById('bts-pin'),
  get btsNotification() {
    return this.btsToggle?.querySelector('.bts-notification-dot');
  },
  get btsCards() {
    return document.querySelectorAll('.bts-card');
  },
  togglePrewarm: document.getElementById('toggle-prewarm'),
  toggleProactive: document.getElementById('toggle-proactive'),
  toggleProactive2: document.getElementById('toggle-proactive2'),
  toggleTransitions: document.getElementById('toggle-transitions'),
  toggleSimulateAIFail: document.getElementById('toggle-simulate-ai-fail'),
  toggleBlandPlaceholder: document.getElementById('toggle-bland-placeholder'),
  temporalMin: document.getElementById('temporal-min'),
  temporalMax: document.getElementById('temporal-max'),
  temporalSliderFill: document.getElementById('temporal-slider-fill'),
  temporalSliderLatest: document.getElementById('temporal-slider-latest'),
  temporalLabelMin: document.getElementById('temporal-label-min'),
  temporalLabelMax: document.getElementById('temporal-label-max'),
  temporalResetBtn: document.getElementById('temporal-reset-btn'),
  metricLabelPrewarm: document.getElementById('metric-label-prewarm'),
  metricPrewarm: document.getElementById('metric-prewarm'),
  metricLabelProactive: document.getElementById('metric-label-proactive'),
  metricProactive: document.getElementById('metric-proactive'),
  metricLabelProactive2: document.getElementById('metric-label-proactive2'),
  metricProactive2: document.getElementById('metric-proactive2'),
  progressContainer: document.getElementById('progress-container'),
  progressFill: document.getElementById('progress-fill'),
  progressPercent: document.getElementById('progress-percent'),
  statusTextSpan: document.getElementById('status-text'),
  errorIcon: document.getElementById('error-info-icon'),
  unavailableIcon: document.getElementById('unavailable-info-icon')
};
